export const items = [
	{ ItemType: "Gear", number: 100 },
	{ ItemType: "Pinion", number: 101 },
	{ ItemType: "Connector", number: 102 },
	{ ItemType: "Bearing", number: 103 },
	{ ItemType: "Spark Plug", number: 104 },
	{ ItemType: "Battery", number: 105 },
	{ ItemType: "Resistor", number: 106 },
	{ ItemType: "Coil", number: 107 },
	{ ItemType: "Turbine", number: 110 },
	{ ItemType: "Fuse", number: 111 },
	{ ItemType: "Power Cell", number: 112 },
	{ ItemType: "Gearbox", number: 113 },
	{ ItemType: "Power Conduit", number: 114 },
	{ ItemType: "Laser", number: 115 },
	{ ItemType: "Data Array", number: 116 },
	{ ItemType: "Flux Capacitor", number: 120 },
	{ ItemType: "Quantum Chip", number: 121 },
	{ ItemType: "Laser Grid", number: 122 },
	{ ItemType: "Photon Gun", number: 123 },
	{ ItemType: "Data Controller", number: 124 },
	{ ItemType: "Tau Thruster", number: 125 },
	{ ItemType: "Time Crystal", number: 130 },
	{ ItemType: "Fusion Reactor", number: 131 },
	{ ItemType: "Tesseract", number: 132 },
	{ ItemType: "Muon Cannon", number: 133 },
	{ ItemType: "Quantum Computer", number: 134 },
	{ ItemType: "Free Mint Pass", number: 403 },
	{ ItemType: "Gold Mint Pass", number: 402 },
	{ ItemType: "Silver Mint Pass", number: 401 },
	{ ItemType: "Bronze Mint Pass", number: 400 },
];